name: CI - Backend
on:
  pull_request:
    paths:
      - "services/backend/LFF.Backend/**/*"
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - name: Build backend
        run:  ls / && cd services/LFF.Backend && docker build -t backend .

