name: CI - Backend
on:
  pull_request:
    paths:
      - "services/backend/LFF.Backend/**/*"
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v3
      - name: Build backend
        run:  >
            cd services/backend/LFF.Backend && \
            docker build -t ghcr.io/ngthvan1612/Learn-English-Thay-Thai/backend . && \
            docker push ghcr.io/ngthvan1612/Learn-English-Thay-Thai/backend

