name: CI - Backend
on:
  pull_request:
    paths:
      - "services/backend/LFF.Backend/**/*"
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    env:
      PAT: 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
    steps:
      - uses: actions/checkout@v3
      - name: Login docker
        run: echo $PAT | docker login ghcr.io -u ngthvan1612 --password-stdin
      - name: Build backend
        run: cd services/backend/LFF.Backend && docker build -t ghcr.io/ngthvan1612/learn-english-thay-thai/backend .
      - name: Push image
        run: docker push ghcr.io/ngthvan1612/learn-english-thay-thai/backend

