name: CI - Frontend Teacher
on:
  pull_request:
    paths:
      - "services/frontend/lff-teacher-template/**/*"
jobs:
  ci-frontend-lff-student:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v3
      - name: Login docker
        run: docker login -u ngthvan1612 -p NguyenVan104
      - name: Build Frontend
        run: cd services/frontend/lff-teacher-template && docker build -t ngthvan1612/learn-english-thay-thai-2023-frontend-teacher .
      - name: Push image
        run: docker push ngthvan1612/learn-english-thay-thai-2023-frontend-teacher
