name: CI - Frontend Admin
on:
  pull_request:
    paths:
      - "services/frontend/lff-staff/**/*"
jobs:
  ci-frontend-lff-staff:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v3
      - name: Login docker
        run: docker login -u ngthvan1612 -p NguyenVan104
      - name: Build Frontend
        run: cd services/frontend/manager && docker build -t ngthvan1612/learn-english-thay-thai-frontend-staff .
